DEBUG 2019-11-07 13:30:25.257 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 13:30:25.258 UTC: 	 Executing command: 'kill'
DEBUG 2019-11-07 13:30:25.258 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-11-07 13:30:25.259 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking2_Run2018A
ERROR 2019-11-07 13:30:25.259 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 584, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 446, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking2_Run2018A
DEBUG 2019-11-07 13:30:25.643 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 13:30:25.644 UTC: 	 Executing command: 'kill'
DEBUG 2019-11-07 13:30:25.644 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-11-07 13:30:25.646 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking3_Run2018A
ERROR 2019-11-07 13:30:25.646 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 584, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 446, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking3_Run2018A
DEBUG 2019-11-07 13:30:26.043 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 13:30:26.043 UTC: 	 Executing command: 'kill'
DEBUG 2019-11-07 13:30:26.043 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-11-07 13:30:26.045 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking4_Run2018A
ERROR 2019-11-07 13:30:26.045 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 584, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 446, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking4_Run2018A
DEBUG 2019-11-07 13:30:26.452 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 13:30:26.452 UTC: 	 Executing command: 'kill'
DEBUG 2019-11-07 13:30:26.453 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-11-07 13:30:26.454 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking5_Run2018A
ERROR 2019-11-07 13:30:26.454 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 584, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 446, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Bparking5_Run2018A
DEBUG 2019-11-07 13:30:26.857 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 13:30:26.857 UTC: 	 Executing command: 'kill'
DEBUG 2019-11-07 13:30:26.857 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-11-07 13:30:26.858 UTC: 	 Error: crab_projects/crab_Bparking6_Run2018A/ is not a valid CRAB project directory.
ERROR 2019-11-07 13:30:26.858 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Bparking6_Run2018A/ is not a valid CRAB project directory.
DEBUG 2019-11-07 14:32:26.997 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 14:32:26.997 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-07 14:32:26.997 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
DEBUG 2019-11-07 14:32:27.006 UTC: 	 Checking credentials
DEBUG 2019-11-07 14:32:27.006 UTC: 	 Found proxy file /tmp/x509up_u112971
DEBUG 2019-11-07 14:32:27.006 UTC: 	 Getting proxy life time left
DEBUG 2019-11-07 14:32:27.812 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -timeleft
 output : 38991

 error: 
 retcode : 0
DEBUG 2019-11-07 14:32:28.822 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -actimeleft
 output : 38989

 error: 
 retcode : 0
DEBUG 2019-11-07 14:32:28.822 UTC: 	 Proxy lifetime 38991 secs is different from voms extension lifetime 38989 secs for proxy: /tmp/x509up_u112971
DEBUG 2019-11-07 14:32:28.822 UTC: 	 Proxy valid for 10:49:49 hours
INFO 2019-11-07 14:32:28.823 UTC: 	 Will use CRAB configuration file crab_Dstar_MC.py
DEBUG 2019-11-07 14:32:28.823 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-11-07 14:32:28.827 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-11-07 14:32:28.828 UTC: 	 Working area '/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Ds_MC_Run2018A' already exists 
Please change the requestName in the config file
ERROR 2019-11-07 14:32:28.828 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 309, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Ds_MC_Run2018A' already exists 
Please change the requestName in the config file
DEBUG 2019-11-07 14:33:23.476 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 14:33:23.477 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-07 14:33:23.477 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
DEBUG 2019-11-07 14:33:23.486 UTC: 	 Checking credentials
DEBUG 2019-11-07 14:33:23.486 UTC: 	 Found proxy file /tmp/x509up_u112971
DEBUG 2019-11-07 14:33:23.486 UTC: 	 Getting proxy life time left
DEBUG 2019-11-07 14:33:24.601 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -timeleft
 output : 38934

 error: 
 retcode : 0
DEBUG 2019-11-07 14:33:25.519 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -actimeleft
 output : 38932

 error: 
 retcode : 0
DEBUG 2019-11-07 14:33:25.519 UTC: 	 Proxy lifetime 38934 secs is different from voms extension lifetime 38932 secs for proxy: /tmp/x509up_u112971
DEBUG 2019-11-07 14:33:25.519 UTC: 	 Proxy valid for 10:48:52 hours
INFO 2019-11-07 14:33:25.520 UTC: 	 Will use CRAB configuration file crab_Dstar_MC.py
DEBUG 2019-11-07 14:33:25.520 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-11-07 14:33:25.524 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-11-07 14:33:25.525 UTC: 	 Working area '/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Ds_MC_Run2018A' already exists 
Please change the requestName in the config file
ERROR 2019-11-07 14:33:25.525 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 309, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects/crab_Ds_MC_Run2018A' already exists 
Please change the requestName in the config file
DEBUG 2019-11-07 14:40:55.079 UTC: 	 Running on: Linux lxplus620.cern.ch 2.6.32-754.23.1.el6.x86_64 #1 SMP Thu Sep 26 11:57:28 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
Description:	Scientific Linux CERN SLC release 6.10 (Carbon)

DEBUG 2019-11-07 14:40:55.079 UTC: 	 Executing command: 'status'
DEBUG 2019-11-07 14:40:55.079 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-11-07 14:40:55.081 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects
ERROR 2019-11-07 14:40:55.081 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 584, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1910.patch2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 446, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_projects
